//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOtomasyonuWeb.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelOtomasyonEntities : DbContext
    {
        public HotelOtomasyonEntities()
            : base("name=HotelOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<THakkimdaSite> THakkimdaSite { get; set; }
        public virtual DbSet<TIletisimSite> TIletisimSite { get; set; }
        public virtual DbSet<TMesajSite> TMesajSite { get; set; }
        public virtual DbSet<TKullaniciSite> TKullaniciSite { get; set; }
        public virtual DbSet<TMisafir> TMisafir { get; set; }
        public virtual DbSet<TRezervasyon> TRezervasyon { get; set; }
        public virtual DbSet<TKMesajSite> TKMesajSite { get; set; }
    }
}
